### ISSUE TITLE
Location button "Follow Me" doesn't call the LocationRequest Class reference 

### ISSUE THREAD

**Issue by Big-jpg** [chris-horner/SocketWeather#25]
Just downloaded the app. Works nice

First screen I'm presented with is a "Follow me" or the "Finding Location" screen, but there is no call made to the LocationRequest Class to request permission to enable GPS for accurate location.

**Comment by chris-horner** [comment]
Thanks for the report. Are you able to provide a little more information on what you mean? The app currently doesn't make use of accurate location updates - only coarse grained.

Are you saying you tap the button and you don't see the permission request dialog?

**Comment by Big-jpg** [comment]
Yeah exactly.

Could just be my device though. I'll QA test tomorrow with a different device.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chris-horner** [comment]
Closing this until any more info comes in.
