### ISSUE TITLE
Location not displayed properly

### ISSUE THREAD

**Issue by k-obrien** [chris-horner/SocketWeather#41]
Selected `Follow me` in Mornington and got what looks like a partially encoded lat/long co-ordinate in the location text

.![Screenshot_20201216-152619.png](https://user-images.githubusercontent.com/53217276/102305426-2574b200-3fb4-11eb-9724-115244b74c1d.png)

**Comment by k-obrien** [comment]
@chris-horner Any objections to requesting fine location if it can mitigate this issue? I know you've avoided doing so before now but assume it just hasn't been necessary.

**Comment by chris-horner** [comment]
It feels a bit dirty for a weather app to know exactly where you are. Wouldn't this issue have more to do with BOM returning rubbish anyway?

**Comment by k-obrien** [comment]
> It feels a bit dirty for a weather app to know exactly where you are.

Fair call.

> Wouldn't this issue have more to do with BOM returning rubbish anyway?

That's been my experience. It was more a hypothetical question, but you also mentioned that testing this will be hard because the emulator doesn't present mocked locations with coarse permissions. I can always request fine solely for testing purposes.

**Comment by chris-horner** [comment]
There's also a list of mock locations you can change in the debug drawer. Might be easier to add another entry there if there's a specific location you want to debug 🙂

**Comment by k-obrien** [comment]
Added the relevant location to debug locator but unable to reproduce. Probably not worth pursuing unless we see it more frequently so happy to close for now.

**Comment by chris-horner** [comment]
Happy to chalk this up to BOM being weird!
