### ISSUE TITLE
Body text is black on About screen in dark mode

### ISSUE THREAD

**Issue by k-obrien** [chris-horner/SocketWeather#52]
When using dark mode, using dynamic colours or not, the body text on the About screen is black.

Device: Pixel 6
OS: Android 13, stock

Great work on 1.0 @chris-horner! I just noticed this minor bug and attempted to fix it myself but quickly noticed it doesn't manifest on the emulator (nor presumably your own devices) so I'm a bit stumped. 🤔 

<img src="https://user-images.githubusercontent.com/53217276/205628887-520f7576-874a-4771-8969-8e8cb66ef49f.png" width="300" />

**Comment by chris-horner** [comment]
[Fixed](https://github.com/chris-horner/SocketWeather/commit/c3cc88ec5e18e1cbf30f8acddff7bc1df2e8b58c) in [1.0.1](https://github.com/chris-horner/SocketWeather/releases/tag/v1.0.1) which fast followed!

**Comment by k-obrien** [comment]
Should have known really. I'll be sure to check the commit log first next time. 😅
