### ISSUE TITLE
Display chance of rain for today's forecast

### ISSUE THREAD

**Issue by chris-horner** [chris-horner/SocketWeather#8]
Probably somewhere up the top section of the home screen.

**Comment by k-obrien** [comment]
I think we can resolve this one.

**Comment by chris-horner** [comment]
Can we? Where do we display chance of rain for today?

**Comment by k-obrien** [comment]
> Can we? Where do we display chance of rain for today?

Sorry, my mistake. I confused it with humidity. 😅

**Comment by chris-horner** [comment]
I make that mistake all the time too! I have plans for some changes to that UI. Just gotta wait for my Diablo 2 addiction to die down and I'll start work on some change 🙂

**Comment by chris-horner** [comment]
Added in [1.0 release](https://github.com/chris-horner/SocketWeather/releases/tag/v1.0.0)
